views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify

import mysql.connector

from datetime import datetime, timedelta

import base64



# Connect to MySQL
connection = mysql.connector.connect(
    host="192.168.68.114",
    user="jordan",
    password="jordan",
    database="Food"
)

views = Blueprint('views', __name__)

## views


# Define a function to calculate the week number based on your definition of a week
def get_week_number(date):
    start_of_week = date - timedelta(days=date.weekday())
    return start_of_week.isocalendar()[1]

@views.route('/')
def home():
    return render_template("index.html")
  
@views.route('/add-recipe', methods=['GET', 'POST'])
def addRecipe():
    if request.method == 'POST':
        data = request.get_json()
        tag_name = data.get('tag_name')

        if tag_name:
            # Insert the new tag into the database
            cursor = connection.cursor()
            cursor.execute("INSERT INTO Tags (TagName) VALUES (%s)", (tag_name,))
            connection.commit()

            # Fetch the ID of the newly inserted tag
            cursor.execute("SELECT LAST_INSERT_ID()")
            new_tag_id = cursor.fetchone()[0]

            cursor.close()

            # Return the ID of the newly inserted tag
            return jsonify({'tag_id': new_tag_id}), 200
        else:
            return jsonify({'error': 'Tag name not provided'}), 400
    else:
        # Fetch tags from the database
        cursor = connection.cursor()
        cursor.execute("SELECT id, tagName FROM Tags ORDER BY TagName")  # Assuming your column names are 'id' and 'tagName'
        tag_names = cursor.fetchall()
        cursor.close()
        # Render the template with tag_names included in the context
        return render_template("add-recipe.html", tag_names=tag_names)




@views.route('/save-recipe', methods=['POST'])
def save_recipe():
    # Extract data from the form
    recipe_name = request.form.get('recipe_name')
    description = request.form.get('description')
    url = request.form.get('url')
    oven_temp = request.form.get('oven_temp')
    time = request.form.get('time')
    tags = request.form.getlist('tags')
    photo = request.files['photo']
    ingredients_name = request.form.getlist('ingredient_name[]')
    instructions = request.form.getlist('instruction[]')
    quantities = request.form.getlist('quantity[]')
    units = request.form.getlist('unit[]')
    categories = request.form.getlist('category[]')
    steps = request.form.getlist('step[]')

    cursor = connection.cursor()

    # Insert into Recipe table
    cursor.execute("INSERT INTO Recipe (RecipeName, Description, URL, OvenTemp, Time) VALUES (%s, %s, %s, %s, %s)",
                   (recipe_name, description, url, oven_temp, time))
    recipe_id = cursor.lastrowid

    # Insert into xRecipeTags table
    for tag_id in tags:
        cursor.execute("INSERT INTO xRecipeTags (RecipeID, TagID) VALUES (%s, %s)", (recipe_id, tag_id))

    # Insert photo into Photos table
    photo_data = photo.read()
    cursor.execute("INSERT INTO Photos (Photo) VALUES (%s)", (photo_data,))
    photo_id = cursor.lastrowid

    # Update PhotoID in Recipe table
    cursor.execute("UPDATE Recipe SET PhotoID = %s WHERE ID = %s", (photo_id, recipe_id))

    # Insert into Ingredients table
    for i in range(len(ingredients_name)):
        cursor.execute("INSERT INTO Ingredients (IngredientName, Instruction, Quantity, Unit, Category) VALUES (%s, %s, %s, %s, %s)",
                       (ingredients_name[i], instructions[i], quantities[i], units[i], categories[i]))
        ingredient_id = cursor.lastrowid
        # Insert into xRecipeIngredients table
        cursor.execute("INSERT INTO xRecipeIngredients (RecipeID, IngredientID) VALUES (%s, %s)", (recipe_id, ingredient_id))

    # Insert into Steps table
    for i in range(len(steps)):
        cursor.execute("INSERT INTO Steps (StepText, StepNumber) VALUES (%s, %s)", (steps[i], i + 1))
        step_id = cursor.lastrowid
        # Insert into xRecipeSteps table
        cursor.execute("INSERT INTO xRecipeSteps (RecipeID, StepsID) VALUES (%s, %s)", (recipe_id, step_id))

    connection.commit()
    cursor.close()

    flash('Recipe saved successfully!', 'success')
    # Redirect to view the saved recipe
    return redirect(url_for('views.view_recipe', recipe_id=recipe_id))

@views.route('/recipe/<int:recipe_id>')
def view_recipe(recipe_id):
    cursor = connection.cursor(dictionary=True)

    # Fetch recipe details including photo ID
    cursor.execute("SELECT * FROM Recipe WHERE ID = %s", (recipe_id,))
    recipe = cursor.fetchone()

    if recipe:
        # Fetch tags associated with the recipe
        cursor.execute("""
            SELECT Tags.TagName
            FROM Tags
            INNER JOIN xRecipeTags ON Tags.ID = xRecipeTags.TagID
            WHERE xRecipeTags.RecipeID = %s
        """, (recipe_id,))
        tags = [tag['TagName'] for tag in cursor.fetchall()]

        # Fetch ingredients for the recipe
        cursor.execute("""
            SELECT Ingredients.IngredientName, Ingredients.Instruction, Ingredients.Quantity, Ingredients.Unit, Ingredients.Category
            FROM Ingredients
            INNER JOIN xRecipeIngredients ON Ingredients.ID = xRecipeIngredients.IngredientID
            WHERE xRecipeIngredients.RecipeID = %s
        """, (recipe_id,))
        ingredients = cursor.fetchall()

        # Group ingredients by category
        ingredients_by_category = {}
        for ingredient in ingredients:
            category = ingredient['Category']
            if category not in ingredients_by_category:
                ingredients_by_category[category] = []
            ingredients_by_category[category].append(ingredient)

        # Fetch steps for the recipe
        cursor.execute("""
            SELECT Steps.StepText
            FROM Steps
            INNER JOIN xRecipeSteps ON Steps.ID = xRecipeSteps.StepsID
            WHERE xRecipeSteps.RecipeID = %s
            ORDER BY xRecipeSteps.ID
        """, (recipe_id,))
        steps = [step['StepText'] for step in cursor.fetchall()]

        # Fetch future weeks available in the database
        cursor.execute("SELECT DISTINCT WeekNumber FROM MealPlans WHERE StartDate >= CURDATE()")
        future_weeks = [week['WeekNumber'] for week in cursor.fetchall()]

        # Fetch photo data based on the photo ID from the recipe
        cursor.execute("SELECT Photo FROM Photos WHERE ID = %s", (recipe['PhotoID'],))
        photo_data = cursor.fetchone()['Photo'] if recipe['PhotoID'] else None

        # Convert photo from bytes to base64
        photo_data_base64 = base64.b64encode(photo_data).decode('utf-8') if photo_data else None

        cursor.close()

        return render_template('recipe.html', recipe=recipe, tags=tags, ingredients_by_category=ingredients_by_category, steps=steps, future_weeks=future_weeks, photo_data_base64=photo_data_base64)
    else:
        # Recipe not found, handle error (e.g., display a message or redirect)
        flash('Recipe not found!', 'error')
        return redirect(url_for('views.index'))  # Assuming you have an index route






@views.route('/recipe/<int:recipe_id>/edit')
def edit_recipe(recipe_id):
    cursor = connection.cursor(dictionary=True)
    
    # Fetch recipe details
    cursor.execute("SELECT * FROM Recipe WHERE ID = %s", (recipe_id,))
    recipe = cursor.fetchone()

    # Fetch tags associated with the recipe
    cursor.execute("""
        SELECT Tags.TagName
        FROM Tags
        INNER JOIN xRecipeTags ON Tags.ID = xRecipeTags.TagID
        WHERE xRecipeTags.RecipeID = %s
    """, (recipe_id,))
    tags = [tag['TagName'] for tag in cursor.fetchall()]

    # Fetch ingredients for the recipe
    cursor.execute("""
        SELECT Ingredients.IngredientName, Ingredients.Instruction, Ingredients.Quantity, Ingredients.Unit, Ingredients.Category
        FROM Ingredients
        INNER JOIN xRecipeIngredients ON Ingredients.ID = xRecipeIngredients.IngredientID
        WHERE xRecipeIngredients.RecipeID = %s
    """, (recipe_id,))
    ingredients = cursor.fetchall()

    # Fetch steps for the recipe
    cursor.execute("""
        SELECT Steps.StepText
        FROM Steps
        INNER JOIN xRecipeSteps ON Steps.ID = xRecipeSteps.StepsID
        WHERE xRecipeSteps.RecipeID = %s
        ORDER BY xRecipeSteps.ID
    """, (recipe_id,))
    steps = [step['StepText'] for step in cursor.fetchall()]

    cursor.close()

    return render_template('edit_recipe.html', recipe=recipe, tags=tags, ingredients=ingredients, steps=steps)

@views.route('/update-recipe/<int:recipe_id>', methods=['GET', 'POST'])
def update_recipe(recipe_id):
    cursor = connection.cursor()

    # Retrieve existing recipe details from the database
    cursor.execute("SELECT * FROM Recipe WHERE ID = %s", (recipe_id,))
    existing_recipe = cursor.fetchone()

    if request.method == 'POST':
        # Extract data from the form
        recipe_name = request.form.get('recipe_name')
        description = request.form.get('description')
        url = request.form.get('url')
        oven_temp = request.form.get('oven_temp')
        time = request.form.get('time')
        tags = request.form.getlist('tags')
        photo = request.files.get('photo')

        # Compare form data with existing recipe data and update if necessary
        if recipe_name != existing_recipe['RecipeName']:
            cursor.execute("UPDATE Recipe SET RecipeName = %s WHERE ID = %s", (recipe_name, recipe_id))

        if description != existing_recipe['Description']:
            cursor.execute("UPDATE Recipe SET Description = %s WHERE ID = %s", (description, recipe_id))

        if url != existing_recipe['URL']:
            cursor.execute("UPDATE Recipe SET URL = %s WHERE ID = %s", (url, recipe_id))

        if oven_temp != existing_recipe['OvenTemp']:

templates/add-recipe.html
{% extends "base.html" %}
<!-- Title -->
{% block title %}Add Recipe{% endblock %}

<!-- Content -->
{% block content %}

<form method="POST" action="/save-recipe" enctype="multipart/form-data">
    <h2>Recipe Details</h2>
    <!-- Recipe Name -->
    
    <input type="text" id="recipe_name" name="recipe_name" maxlength="50" required placeholder="Recipe Name"><br>

    <!-- Description -->
    
    <textarea id="description" name="description" maxlength="500" rows="4" cols="50" placeholder="Description"></textarea><br>

    
<!-- URL -->

<input type="text" id="url" name="url" placeholder="URL"><br>

<!-- Oven Temp -->

<input type="number" id="oven_temp" name="oven_temp" placeholder="Oven Temp"><br>

<!-- Time -->

<input type="text" id="time" name="time" placeholder="Time"><br>

    <!-- Tags -->
    <h2>Tags</h2>
    <div id="tag-section">
        <!-- Existing tags -->
        {% for tag_id, tag_name in tag_names %}
            <input type="checkbox" id="tag_{{ tag_id }}" name="tags" value="{{ tag_id }}">
            <label for="tag_{{ tag_id }}">{{ tag_name }}</label><br>
        {% endfor %}

        <!-- Add new tag input -->
        <ul id="tag-list">
            <!-- Tag list will be dynamically populated here -->
        </ul>
    </div>
    <!-- Photo Upload -->
    <h2>Photo</h2>
    <input type="file" id="photo" name="photo" accept="image/*"><br>




<!-- Ingredients -->
<h2>Ingredients</h2>
<div id="ingredients">
    <!-- Initial ingredient fields -->
    <div class="ingredient">
        <input type="text" name="ingredient_name[]" placeholder="Ingredient Name">
        <input type="text" name="instruction[]" placeholder="Instruction">
        <input type="text" name="quantity[]" placeholder="Quantity">
        <input type="text" name="unit[]" placeholder="Unit">
        <input type="text" name="category[]" placeholder="Category">
     </div>
</div>
<button type="button" id="add_ingredient">Add Ingredient</button><br>

<!-- Steps -->
<h2>Steps</h2>
<div id="steps">
    <!-- Initial instruction field -->
    <div>
        <textarea class="steps" name="step[]" maxlength="256" rows="4" cols="50" placeholder="Step 1"></textarea>
    </div>
</div>
<button type="button" id="add_step">Add Step</button><br>
<input type="hidden" id="step_count" name="step_count" value="1">

<!-- Save Button -->
<button type="submit">Save Recipe</button>


<!-- CSS Ref -->
<link rel="stylesheet" href="{{ url_for('static', filename='addrecipe.css')}}">

<!-- JS Ref-->
<script type="text/javascript" src="{{ url_for('static', filename='addrecipe.js')}}"></script>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <!-- Title -->   
    <title>{% block title %}{% endblock title %}</title>
    <!-- CSS Ref -->
    <link rel="stylesheet" href="/static/navbar.css">
</head>
<body>
 <!-- NavBar -->
 <div class="navbarcontainer">
<div class="navbar">
    <div class="menu-icon" onclick="toggleMenu()">
      <div class="bar"></div>
      <div class="bar"></div>
      <div class="bar"></div>
    </div>
    <div class="menu-links" id="menuLinks">
      <a href="{{ url_for('views.addRecipe') }}" class="page-link-button">Add Recipe ➕</a>
      <a href="{{ url_for('views.search') }}" class="page-link-button">Search 🔍</a>
      <a href="{{ url_for('views.tags') }}" class="page-link-button">Tags 🏷️</a>
      <a href="{{ url_for('views.mealPlanner') }}" class="page-link-button">Meal Planner 📆 </a>
      <a href="{{ url_for('views.shopping_lists') }}" class="page-link-button">Shopping Lists 📝</a>
    </div>
    </div>
</div>

<div class="space"></div>
    
    <script type="text/javascript" src="{{ url_for('static', filename='navbar.js')}}"></script>

    {% block content %}
    {% endblock %}
</body>
</html>

templates/edit_recipe.html
{% extends "base.html" %}
{% block title %}Edit Recipe - {{ recipe.RecipeName }}{% endblock %}
{% block content %}
    <h2>Edit Recipe - {{ recipe.RecipeName }}</h2>
    <form method="POST" action="{{ url_for('views.update_recipe', recipe_id=recipe.ID) }}" enctype="multipart/form-data">

        <!-- Recipe Name -->
        <label for="recipe_name">Recipe Name:</label>
        <input type="text" id="recipe_name" name="recipe_name" value="{{ recipe.RecipeName }}"><br><br>
        
        <!-- Description -->
        <label for="description">Description:</label>
        <textarea id="description" name="description">{{ recipe.Description }}</textarea><br><br>
        
        <!-- URL -->
        <label for="url">URL:</label>
        <input type="text" id="url" name="url" value="{{ recipe.URL }}"><br><br>
        
        <!-- Oven Temperature -->
        <label for="oven_temp">Oven Temperature:</label>
        <input type="text" id="oven_temp" name="oven_temp" value="{{ recipe.OvenTemp }}"><br><br>
        
        <!-- Time -->
        <label for="time">Time:</label>
        <input type="text" id="time" name="time" value="{{ recipe.Time }}"><br><br>
        
        <!-- Tags -->
        <label>Tags:</label><br>
        {% for tag_name in tag_names %}
            <input type="checkbox" id="tag_{{ loop.index }}" name="tags" value="{{ loop.index }}" {% if tag_name in tags %} checked {% endif %}>
            <label for="tag_{{ loop.index }}">{{ tag_name }}</label><br>
        {% endfor %}
        <br>
        
        <!-- Photo -->
        <label for="photo">Photo:</label>
        <input type="file" id="photo" name="photo"><br><br>
        
        <!-- Ingredients -->
        <label for="ingredients">Ingredients:</label><br>
        <div id="ingredient-container">
            {% for ingredient in ingredients %}
                <div class="ingredient">
                    <input type="text" name="ingredient_name[]" value="{{ ingredient.IngredientName }}" placeholder="Ingredient Name">
                    <input type="text" name="instruction[]" value="{{ ingredient.Instruction }}" placeholder="Instruction">
                    <input type="text" name="quantity[]" value="{{ ingredient.Quantity }}" placeholder="Quantity">
                    <input type="text" name="unit[]" value="{{ ingredient.Unit }}" placeholder="Unit">
                    <input type="text" name="category[]" value="{{ ingredient.Category }}" placeholder="Category">
                    <button type="button" class="remove-ingredient">Remove</button><br>
                </div>
            {% endfor %}
        </div>
        <button type="button" id="add-ingredient">Add Ingredient</button>
        <br>

        <!-- Steps -->
        <label for="steps">Steps:</label><br>
        <div id="step-container">
            {% for step in steps %}
                <div>
                    <textarea name="step[]" value="{{ step }}">{{ step }}</textarea>
                    <input type="hidden" name="step_id_{{ loop.index }}" value="{{ step.ID }}">
                    <button type="button" class="remove-step">Remove</button><br>
                </div>
            {% endfor %}
        </div>
        <button type="button" id="add-step">Add Step</button>
        <br>
        
        <button type="submit">Save Changes</button>
    </form>
    
    <!-- Include jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Include custom JavaScript -->
    <script src="{{ url_for('static', filename='editrecipe.js')}}"></script>

{% endblock %}

templates/htmltemplate.html
{% extends "base.html" %}
<!-- Title -->
{% block title %}{% endblock %}

<!-- Content -->
{% block content %}

<!-- CSS Ref -->
<link rel="stylesheet" href="/static/">

{% endblock %}

templates/index.html
{% extends "base.html" %}
<!-- Title -->
{% block title %}{% endblock %}

<!-- Content -->
{% block content %}



{% endblock %}

templates/ingredients.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Ingredient Tracker</title>
<link rel="stylesheet" href="/static/ingredients.css">
</head>
<body>
  <div class="container">
    <h1>Add New Ingredient</h1>
    <form action="/ingredients" method="POST"> <!-- Added form tag -->
      <input type="text" id="ingredient" name="ingredient" placeholder="Ingredient">
      <input type="text" id="instructions" name="instructions" placeholder="Instructions">
      <input type="number" id="quantity" name="quantity" placeholder="Quantity">
      <input type="text" id="unit" name="unit" placeholder="Unit">
      <input type="text" id="category" name="category" placeholder="Category">
      <button type="submit">Add Ingredient</button> <!-- Changed to type="submit" -->
    </form>
    <table id="ingredientTable">
      <thead>
        <tr>
          <th>Ingredient</th>
          <th>Instructions</th>
          <th>Quantity</th>
          <th>Unit of Measurement</th>
          <th>Category</th>
        </tr>
      </thead>
      <tbody id="ingredientBody">
        {% for ingredient in ingredients %}
        <tr data-id="{{ ingredient[0] }}"> <!-- Added data-id attribute -->
            <td>{{ ingredient[1] }}</td>
            <td>{{ ingredient[2] }}</td>
            <td>{{ ingredient[3] }}</td>
            <td>{{ ingredient[4] }}</td>
            <td>{{ ingredient[5] }}</td>
            <td><button onclick="deleteIngredient('{{ ingredient[0] }}')">Delete</button></td>
        </tr>
        {% endfor %}
    </tbody>
    
  </div>

  <script type="text/javascript" src="{{ url_for('static', filename='ingredients.js')}}"></script>
</body>
</html>

templates/mealplanner.html
{% extends "base.html" %}
<!-- Title -->
{% block title %}Meal Planner{% endblock %}

<!-- Content -->
{% block content %}

<!-- CSS Ref -->
<link rel="stylesheet" href="{{ url_for('static', filename='mealplanner.css')}}">

<h2>Meal Planner</h2>

<!-- Form to add a new week -->
<form action="{{ url_for('views.add_week_to_meal_planner') }}" method="POST">
    <label for="start_date">Start Date:</label>
    <input type="date" id="start_date" name="start_date" required>
    <button type="submit">Add Week</button>
</form>

<!-- Loop through meal plans and display each week along with the "Add New Recipe" button -->
{% for meal_plan in meal_plans %}
    {% if meal_plan.EndDate >= current_date %}
        <div class="week-container {% if meal_plan.WeekNumber == current_week %}current-week{% endif %}">
            <h3>Week {{ meal_plan.WeekNumber }} ({{ meal_plan.StartDate.strftime('%d/%m') }} to {{ meal_plan.EndDate.strftime('%d/%m') }})</h3>
            <a href="{{ url_for('views.recipe_listing', week_number=meal_plan.WeekNumber) }}"><button>Add New Recipe</button></a>
            <!-- Display recipes in a grid -->
            <div class="recipe-grid">
                {% for recipe in meal_plan.recipes %}
                    <div class="recipe-item">
                        <a href="{{ url_for('views.view_recipe', recipe_id=recipe.ID) }}">
                            <img class="recipe-photo" src="data:image/jpeg;base64,{{ recipe.RecipePhoto }}" alt="Recipe Photo">
                        </a>
                        <p class="recipe-name">
                            <a href="{{ url_for('views.view_recipe', recipe_id=recipe.ID) }}">{{ recipe.RecipeName }}</a>
                        </p>
                        <!-- Add remove button -->
                        <form action="{{ url_for('views.remove_recipe_from_week', recipe_id=recipe.ID, week_number=meal_plan.WeekNumber) }}" method="POST">
                            <button type="submit">Remove</button>
                        </form>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endfor %}


{% endblock %}

templates/recipe.html
{% extends "base.html" %}
<!-- Title -->
{% block title %}{{ recipe.RecipeName }}{% endblock %}

<!-- Content -->
{% block content %}

    <h2>{{ recipe.RecipeName }}</h2>
    <div class="recipe-photo">
        {% if photo_data_base64 %}
    <img src="data:image/jpeg;base64,{{ photo_data_base64 }}" alt="Recipe Photo">
{% endif %}
    </div>
    
    <p>{{ recipe.Description }}</p>
    <p><a href="url" style="color: white;">{{ recipe.URL }}</a></p>

    
    
    <h3>Tags</h3>
    <div class="tags-grid">
        {% for tag in tags %}
            <a href="{{ url_for('views.recipes_by_tag', tag_name=tag) }}" class="tag">{{ tag }}</a>
        {% endfor %}
    </div>
    
    <h3>Ingredients</h3>
    <table class="ingredient-table">

        <tbody>
            {% for category, ingredient_list in ingredients_by_category.items() %}
                <tr>
                    <td colspan="3"><span class="category"><h4>{{ category }}</h4></span></td>
                </tr>
                {% for ingredient in ingredient_list %}
                <tr>
                    <td><span class="quantity">{{ ingredient.Quantity }}{{ ingredient.Unit }} </span></td>
                    <td class="ingredient-name">&nbsp; {{ ingredient.IngredientName }} </td>
                    <td class="instruction">{{ ingredient.Instruction }}</td>
                </tr>
                
                {% endfor %}
            {% endfor %}
        </tbody>
    </table>

        

    <h3>Method</h3>
            
    <p><strong>Oven Temperature</strong> {{ recipe.OvenTemp }}°C</p>
    <p><strong>Time</strong> {{ recipe.Time }}</p>
    
    <ol>
        {% for step in steps %}
            <li>{{ step }}</li>
        {% endfor %}
    </ol>

    <!-- Form to add recipe to a week on the meal planner -->
<h3>Add to Meal Planner</h3>
<form action="{{ url_for('views.add_to_meal_planner') }}" method="post">
    <input type="hidden" name="recipe_id" value="{{ recipe.ID }}">
    <label for="week_number">Select Week</label>
    <select name="week_number" id="week_number">
        {% for week_number in future_weeks %}
            <option value="{{ week_number }}">Week {{ week_number }}</option>
        {% endfor %}
    </select>
    <button type="submit">Add to Week</button>
</form>

<!-- CSS Ref -->
<link rel="stylesheet" href="{{ url_for('static', filename='recipe.css')}}">

{% endblock %}

templates/recipe_details.html
{% extends "base.html" %}
{% block title %}{{ recipe.recipeName }}{% endblock %}

{% block content %}

  <h1>{{ recipe.recipeName }}</h1>
  <p>Description: {{ recipe.description }}</p>
  <p>Link: <a href="{{ recipe.link }}">{{ recipe.link }}</a></p>
  <p>Oven Temperature: {{ recipe.ovenTemp }}</p>
  <p>Time: {{ recipe.time }}</p>
  
  <h2>Ingredients</h2>
  <table>
      <thead>
          <tr>
              <th>Ingredient</th>
              <th>Instructions</th>
              <th>Quantity</th>
              <th>Unit</th>
              <th>Category</th>
          </tr>
      </thead>+
      <tbody>
 
      </tbody>
  </table>
  
  
  
  
  
  <h2>Steps</h2>
  <ol>
      {% for step in steps %}
          <li>{{ step.stepText }}</li>
      {% endfor %}
  </ol>

{% endblock %}

templates/recipe_listing.html
{% extends "base.html" %}
<!-- Title -->
{% block title %}Recipe Listing{% endblock %}
<!-- CSS Ref -->



<!-- Content -->
{% block content %}
<div class="container">
    <h2>Recipe Listing for Week {{ week_number }}</h2>
    
    <!-- Search Form -->
    <form action="{{ url_for('views.recipe_listing', week_number=week_number) }}" method="GET">
        <label for="search_query">Search by Recipe Name or Tags</label>
        <input type="text" id="search_query" name="search_query">
        <button type="submit">Search</button>
    </form>
    
    <!-- Display Filtered Recipes -->
    <div class="recipe-grid">
        {% for recipe in recipes %}
            <div class="recipe-item">
                <a href="{{ url_for('views.view_recipe', recipe_id=recipe.ID) }}">
                    <img class="recipe-photo" src="data:image/jpeg;base64,{{ recipe.Photo }}" alt="Recipe Photo">
                </a>
                <p class="recipe-name">
                    <a href="{{ url_for('views.view_recipe', recipe_id=recipe.ID) }}">{{ recipe.RecipeName }}</a>
                </p>
                <form action="{{ url_for('views.add_recipe_to_meal_planner', recipe_id=recipe.ID, week_number=week_number) }}" method="POST">
                    <button type="submit">Add to Week {{ week_number }}</button>
                </form>
            </div>
        {% endfor %}
    </div>
</div>

<link rel="stylesheet" href="/static/recipelisting.css">
{% endblock %}

templates/recipes_by_tag.html
{% extends "base.html" %}
<!-- Title -->
{% block title %}Recipes for {{ tag_name }}{% endblock %}

<!-- Content -->
{% block content %}
<link rel="stylesheet" href="/static/recipetags.css"> <!-- Link to your CSS file -->
    <h2>Recipes for {{ tag_name }}</h2>
    <div class="recipe-grid">
        {% for recipe in recipes %}
            <div class="recipe-item">
                <a href="{{ url_for('views.view_recipe', recipe_id=recipe.ID) }}">
                    {% if recipe.Photo %}
                        <img class="recipe-photo" src="data:image/jpeg;base64,{{ recipe.Photo }}" alt="Recipe Photo">
                    {% endif %}
                    <p class="recipe-name">{{ recipe.RecipeName }}</p>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}